services:
  db:
    container_name: bdr_postgresql_16
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=trustno1
      - POSTGRES_DB=bdr_project
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-scripts:/docker-entrypoint-initdb.d/
    networks:
      - bdr_network

  web:
    container_name: bdr_web_16
    image: bdr_web
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app/src
    networks:
      - bdr_network

volumes:
  pgdata:

networks:
  bdr_network:
